### ISSUE TITLE
Enhancement - create interface to load a super mario maker level

### ISSUE THREAD

**Issue by johndpope** [cocoatoucher/Glide#2]
https://github.com/Gummygamer/smmmlevels
There's some work here to procedurally create levels by transferring them into text.
If you could somehow allow a plug in ability - to mario backgrounds - this would open up worlds for game developers / designers. 
Consider this maybe a 'help wanted' ticket. 

![](https://user-images.githubusercontent.com/289994/53910669-81549c00-40a8-11e9-91dc-f4d8e0960dac.png)

would need to be able to load a cdt and convert into appropriate layout for Glide.

**Comment by johndpope** [comment]
There's a method called
level.toAIString

I think this will provide a simple way to populate a swift / sprite level 


    def toAIString(self):
        aiString = ""
        
        #level grid loop
        #could be optimized
        for i in range(0,239):
            for j in range(0,26):
                present = False
                for spr in self.sprites:
                    if (math.floor(spr.objx / 16) == i) and (math.floor(spr.objy / 16) == j):
                        aiString += spr.toAIChar()
                        present = True
                if (present == False):
                    aiString += " "
        
        return aiString

**Comment by cocoatoucher** [comment]
Hey,
Sorry for the delayed response. I think that looks really interesting. I wasn't aware that Super Mario Maker had open files like that. Looking forward to Nintendo Switch version by the way! 🙂
I'm still not aware of many details but I think glide should support importing functionality from as many editors as possible, if to see Super Mario Maker as a level editor as well. 
I implemented a similar functionality for Tiled Map Editor map files. You can check it out here: https://github.com/cocoatoucher/Glide/blob/master/Shared/TiledMapEditorSceneLoader/TiledMapEditorSceneLoader.swift
That one imports json map files you create in Tiled Map Editor (https://www.mapeditor.org)
However, that is basically not glide specific and it'd work on any SpriteKit game. Since glide is SpriteKit based, this converts the contents of json file to a SKTileMapNode instance with some additional specific properties only recognized by glide. 

Do you think that is close to what you are looking for? I can give any support needed if you start writing a parser for cdt files. If we could start with converting contents of a cdt file to a SKTileMapNode, that would be a great step.

I have some questions though.
- Does Super Mario Maker also give access to their art assets? When we are populating a tile map node via the parser, will we be able to populate it with the assets used in the game, or do we need to add support for picking replacement assets?
- How can I export a cdt file from a Super Mario Maker on a 3ds?

Thanks for sharing this and looking forward to your response.

**Comment by johndpope** [comment]
short answer is - you'll need to google -  "SMM ROM link" and dig around for 700 MB file to grab assets needed to visualize level with python code below to get RoadrunnerWMC level editor working. There are numbers / codes associated with these parts within level. 

https://github.com/RoadrunnerWMC/Metamaker/pull/1#issuecomment-470702659

I dug around github - there's other code that makes use of a generated png file of sprites
 eg. MW_Field_hauntedhouse.png / as opposed to the  MW_Field_hauntedhouse.szs (which are zipped and compressed binary specific to nintendo) 

https://github.com/AuriRex/SMM-LDE/
<img width="514" alt="Screen Shot 2019-05-27 at 21 48 52" src="https://user-images.githubusercontent.com/289994/58417786-42434f00-80c9-11e9-8b8f-231222989e84.png">

These assets are "highly copyrighted" - so yeah - as you suggested - we'll want to be able to pick the assets.  To rebuild a parser - may not be worth effort if you can hot wire some png. Maybe can cherry pick java code above - or have user run some python script from Metamaker ? 

My imagination was - I want to use Glide - and leverage the level designed by mario maker - 
create my own characters / my own enemies / my own colors / fonts etc.....

**Comment by johndpope** [comment]
![Screen Shot 2019-05-28 at 11 34 16 am](https://user-images.githubusercontent.com/289994/58444684-ac490c00-813c-11e9-92bd-85de171aa62b.png)
it's possible to convert project to kotlin / which is kind of swifty. CMD + ALT + SHIFT +K 

![Screen Shot 2019-05-28 at 11 36 22 am](https://user-images.githubusercontent.com/289994/58444714-d69ac980-813c-11e9-93da-300039fdf543.png)

sample SMMLevels.java -> kotlin
https://gist.github.com/johndpope/6b5174539ba1da40530e4c183af0760f
