### ISSUE TITLE
Using Glide with Xcode 11?

### ISSUE THREAD

**Issue by gerchicov-bp** [cocoatoucher/Glide#3]
In Xcode 11 project structure differs greatly from Xcode 10. Could you explain how to prepare a project in it with SwiftUI and/or Storyboard?

**Comment by cocoatoucher** [comment]
Hey,
There is no SwiftUI support in Glide Engine yet, and the tutorial below creates most UI components programmatically.
You can watch the starter tutorial here: https://www.youtube.com/watch?v=Fx7Cv6-WjMQ
The tutorial uses Xcode 10, but since it uses the `Cross-platform` -> `Empty` template, this shouldn't be a problem. I think what Xcode 11 doesn't do is creating targets for you which you can create from your project settings. Also, now you can use Glide Engine Swift package instead of Cocoapod, which should make things easier.
Please let me know if you have specific questions from the tutorial.
